### ISSUE TITLE
Code chunks' white background got removed when using Hugo Apero with R package Flair

### ISSUE THREAD

**Issue by JauntyJJS** [hugo-apero/hugo-apero#51] opened 2021-09-11 14:49 UTC
Hi,

I am trying to highlight the R source code in the Hugo Apero using the R package [Flair](https://r-for-educators.github.io/flair/articles/how_to_flair.html)

This is how it look likes without adding any flair function

![image](https://user-images.githubusercontent.com/9066508/132951594-2a59158b-5a0a-4807-92e1-2e9fb50e6857.png)

Adding the flair function 

gives this

![image](https://user-images.githubusercontent.com/9066508/132951661-28533f28-b37c-49e2-b3af-fd09a9aec633.png)

It seems that the white background in the code chunk area got removed.

Is there a way to add it back ?

**Comment by harshvardhaniimi** [comment] 2021-11-08 01:36
I am unable to reproduce the issue. [Following screenshots for codes is tedious](https://yihui.org/en/2018/01/screenshots-vs-text/). Can you update the post with codes or the appropriate markdown file (not .Rmd but .md)?

**Comment by JauntyJJS** [comment] 2021-11-12 13:10
Hi, Sorry for the late reply. I just read this message after returning from reservist training. I will try to submit the code by tomorrow. Thank you.

**Comment by JauntyJJS** [comment] 2021-11-13 02:29
Attached is the code
[index.zip](https://github.com/hugo-apero/hugo-apero/files/7531254/index.zip)
.

**Comment by harshvardhaniimi** [comment] 2021-11-13 17:11
I am still unable to replicate the issue. Here's what I tried. When I compile the file you posted, I get the following error.
```
Error: YAML output format must evaluate to a function
Execution halted
```
This is likely from `hugodown`. When I tried compiling it to a `.md`, line 49 gives me another error, which I suspect was an [issue](https://github.com/r-for-educators/flair/issues/13) with `flair` in newer versions of R (4+), fixed [later](https://github.com/r-for-educators/flair/pull/14).

```
Error in viewer(htmlFile) : could not find function "viewer"
Calls: <Anonymous> ... knit_print.default -> normal_print -> print -> print.with_flair
Execution halted
```

Adding `knit_print.with_flair()` did not work either. Now the error is:

```
Error in if (doc_type == "pdf_document") { : argument is of length zero
Calls: <Anonymous> ... %>% -> knit_print.with_flair -> map -> .f -> prep_source
Execution halted
```

I don't know what could result in this [argument error](https://stackoverflow.com/questions/27350636/r-argument-is-of-length-zero-in-if-statement) here. Can you tell me your sessionInfo (`utils::sessionInfo()`)? Also, have you tried reducing dependencies (like `hugodown`) and see if it still throws an error?

Throwing a dart in dark, but it might be that [hugodown](https://github.com/r-lib/hugodown#compared-to-blogdown) doesn't support this theme yet.

**Comment by JauntyJJS** [comment] 2021-11-15 14:36
Hi,

My session info is as follows

```
> utils::sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_Singapore.1252  LC_CTYPE=English_Singapore.1252   
[3] LC_MONETARY=English_Singapore.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Singapore.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] ggplot2_3.3.5       dplyr_1.0.7         flair_0.0.2         xaringanExtra_0.5.5

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7          compiler_4.1.1      pillar_1.6.2        later_1.3.0         tools_4.1.1        
 [6] digest_0.6.28       uuid_0.1-4          gtable_0.3.0        tibble_3.1.4        jsonlite_1.7.2     
[11] evaluate_0.14       lifecycle_1.0.1     pkgconfig_2.0.3     rlang_0.4.11        cli_3.0.1          
[16] rstudioapi_0.13     yaml_2.2.1          blogdown_1.5        xfun_0.26           fastmap_1.1.0      
[21] withr_2.4.2         stringr_1.4.0       knitr_1.34          generics_0.1.0      fs_1.5.0           
[26] vctrs_0.3.8         grid_4.1.1          tidyselect_1.1.1    glue_1.4.2          R6_2.5.1           
[31] processx_3.5.2      fansi_0.5.0         rmarkdown_2.11      bookdown_0.24       hugodown_0.0.0.9000
[36] farver_2.1.0        purrr_0.3.4         magrittr_2.0.1      servr_0.23          scales_1.1.1       
[41] ps_1.6.0            promises_1.2.0.1    htmltools_0.5.2     ellipsis_0.3.2      colorspace_2.0-2   
[46] renv_0.14.0         httpuv_1.6.2        labeling_0.4.2      utf8_1.2.2          stringi_1.7.4      
[51] munsell_0.5.0       crayon_1.4.1   
```

Unfortunately, I do not know how to reduce `hugodown` as a dependencies due to limited knowledge about R

**Comment by harshvardhaniimi** [comment] 2021-11-15 14:38
I need to look at it more closely but reducing `hugodown` dependencies is simple. Remove output: `hugodown::md_document()` from YAML of your documents.

**Comment by JauntyJJS** [comment] 2021-11-22 13:01
Noted with thanks. Attached is the file with the `output: hugodown::md_document()` 
[index.zip](https://github.com/hugo-apero/hugo-apero/files/7581135/index.zip)

**Comment by apreshill** [comment] 2022-01-11 17:52
Thank you @harshvardhaniimi! @JauntyJJS did this resolve your issue? If so, can you please close it?

**Closed** 2022-01-12 01:30 UTC
Labels: question
